version: "2"

services:
  php:
    build:
      context: .
      dockerfile: ./DockerfilePhp
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./DockerfileNginx
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "1111:80"
    env_file:
      - .env
  dbpg:
    image: postgres
    restart: always
    volumes:
     - ./docker-runtime/postgres:/var/lib/postgresql/data
    environment:
     POSTGRES_PASSWORD: password
     POSTGRES_USER: user
     POSTGRES_DB: db

  mysql:
    #image: mysql:latest
    build:
      context: .
      dockerfile: ./DockerfileMysql
    restart: always
    volumes:
      - ./docker-runtime/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env